package com.sitionix.forgeit.processor;

import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;

import javax.annotation.processing.FilerException;
import javax.annotation.processing.Messager;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.Modifier;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import javax.tools.StandardLocation;
import java.io.IOException;
import java.io.Writer;
import java.util.Set;

final class GeneratedInterfaceEmitter {

    private final ProcessingEnvironment processingEnv;
    private final Messager messager;
    private final ClassName generatedType;

    private boolean featuresGenerated;
    private String lastEmittedSignature = "";

    GeneratedInterfaceEmitter(ProcessingEnvironment processingEnv, Messager messager, ClassName generatedType) {
        this.processingEnv = processingEnv;
        this.messager = messager;
        this.generatedType = generatedType;
    }

    void generateInterface(Set<String> aggregatedSupports) {
        final String signature = String.join("\n", aggregatedSupports);
        if (!featuresGenerated) {
            emitInterface(aggregatedSupports, signature);
            return;
        }

        if (!lastEmittedSignature.equals(signature)) {
            try {
                processingEnv.getFiler()
                        .getResource(StandardLocation.SOURCE_OUTPUT,
                                generatedType.packageName(),
                                generatedType.simpleName() + ".java")
                        .delete();
            } catch (IOException ignored) {
                // best-effort delete; if it fails we'll try overwriting below
            }
            emitInterface(aggregatedSupports, signature);
        }
    }

    private void emitInterface(Set<String> aggregatedSupports, String signature) {
        TypeSpec.Builder typeBuilder = TypeSpec.interfaceBuilder(generatedType.simpleName())
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("Generated by {@link $L}.\n", ForgeFeaturesProcessor.class.getName());

        for (String support : aggregatedSupports) {
            typeBuilder.addSuperinterface(ClassName.bestGuess(support));
        }

        JavaFile javaFile = JavaFile.builder(generatedType.packageName(), typeBuilder.build())
                .skipJavaLangImports(true)
                .build();

        try {
            JavaFileObject sourceFile = processingEnv.getFiler().createSourceFile(
                    generatedType.packageName() + "." + generatedType.simpleName());
            try (Writer writer = sourceFile.openWriter()) {
                javaFile.writeTo(writer);
            }
            featuresGenerated = true;
            lastEmittedSignature = signature;
        } catch (FilerException ex) {
            messager.printMessage(Diagnostic.Kind.ERROR,
                    "ForgeIT features interface already exists and could not be replaced: " + ex.getMessage());
        } catch (IOException ex) {
            messager.printMessage(Diagnostic.Kind.ERROR,
                    "Failed to generate ForgeIT features interface: " + ex.getMessage());
        }
    }
}
